version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3001:3000"

  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    image: "node:10-alpine"
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend
