version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - EDITOR=vim

  frontend:
    build:
      context: "frontend"
    image: "node:14-alpine"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  nginx:
    image: nginx:stable
    ports: 
      - 80:80
    volumes:
      - ./frontend/public:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  mysql_data:
    driver: local